language: ruby
bundler_args: --without development
script: 'rake appraisal test'
rvm:
- 2.0.0
env:
- DB=mongodb
- DB=redis
- DB=mysql
#- DB=postgres
before_script:
- "mysql -e 'create database vanity_test;' >/dev/null"
- "rake appraisal:install"
#- "psql -c 'create database vanity_test;' -U postgres >/dev/null"
